name: Production Builds
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
            log-accepted-android-sdk-licenses: 'false'

    #   # This will decode the keystore from base 64 text representation that we have stored in secrets
    #   # and generates and keystore file and gets stored in /android-app path
    #   - name: Decode Keystore
    #     env:
    #       ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
    #       RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
    #       RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
    #       RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

    #     run: |
    #       echo $ENCODED_STRING > keystore-b64.txt
    #       base64 -d keystore-b64.txt > keystore.jks

    #   - name: Change to project directory
    #     run: cd TestApp
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build Release apk
        # env:
        #   RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        #   RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
        #   RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease bundleRelease --stacktrace

      - name: Find and upload APKs
        run: |
            $apkPath = Get-ChildItem -Recurse -Filter *.apk | Where-Object { $_.Name -like "*release*" } | Select-Object -First 1 -ExpandProperty FullName
            echo "APK_PATH=$apkPath" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Upload Release APKs to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: ${{ env.APK_PATH }}

      - name: Find and upload AABs
        run: |
            $aabPath = Get-ChildItem -Recurse -Filter *.aab | Where-Object { $_.Name -like "*release*" } | Select-Object -First 1 -ExpandProperty FullName
            echo "AAB_PATH=$aabPath" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Upload Release AABs to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-aabs
          path: ${{ env.AAB_PATH }}

